[package]
name = "config-loader"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
keywords = ["web", "env"]
categories = ["env", "server", "web"]

[dependencies]
dotenv = { version = "0.15" }
